djangock/apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path(
        '',
        views.PostEntryListView.as_view(),
        name='index'
    ),
    path(
        'new/',
        views.PostEntryCreateView.as_view(),
        name='create'
    ),
    path(
        'read/<str:slug>/',
        views.PostEntryDetailView.as_view(),
        name='detail'
    ),
    path(
        'update/<str:slug>/',
        views.PostEntryUpdateView.as_view(),
        name='update'
    ),
]

djangock/djangock/urls.py
"""djangock URL Configuration
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
"""
from django.urls import include, path

urlpatterns = [
    path('', include('apps.blog.urls', namespace='blog')),
]

djangock/apps/blog/models.py
from django.db import models
from django.template.defaultfilters import slugify


class PostEntry(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(default='This is a new post')
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        self.slug = slugify(self.title[:50])
        super().save(**kwargs)

djangock/apps/blog/forms.py
from django import forms

from apps.blog.models import PostEntry


class PostEntryModelForm(forms.ModelForm):
    class Meta:
        model = PostEntry
        fields = (
            'title',
            'text',
        )

djangock/apps/blog/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from apps.blog.forms import PostEntryModelForm
from apps.blog.models import PostEntry


class PostEntryListView(ListView):
    template_name = 'index.html'
    model = PostEntry
    paginate_by = 20


class PostEntryDetailView(DetailView):
    template_name = 'view_post.html'
    model = PostEntry
    slug_url_kwarg = 'slug'
    slug_field = 'slug'


class PostEntryCreateView(CreateView):
    template_name = 'create_edit.html'
    form_class = PostEntryModelForm
    success_url = reverse_lazy('blog:index')


class PostEntryUpdateView(UpdateView):
    template_name = 'create_edit.html'
    form_class = PostEntryModelForm
    model = PostEntry
    slug_url_kwarg = 'slug'
    slug_field = 'slug'

    def get_success_url(self):
        success_url = reverse('blog:detail', args=[self.object.slug])
        return success_url

djangock/apps/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Your awesome blog</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  {% block css %}{% endblock %}
</head>
<body>
<div class="container">
  {% block content %}{% endblock %}
</div>
{% block scripts %}{% endblock %}
</body>
</html>

djangock/apps/blog/templates/create_edit.html
{% extends 'base.html' %}
{% block content %}
  <h3>New post entry</h3>
  <form action="." method="post" enctype="multipart/form-data" id="postForm">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">
        {{ form.as_p }}
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <button type="submit" class="btn btn-success btn-block" id="submit">
          Save
        </button>
      </div>
    </div>
  </form>
{% endblock %}
{% block scripts %}
  <script src="https://cdn.ckeditor.com/ckeditor5/12.1.0/classic/ckeditor.js"></script>
  <script>
    ClassicEditor
      .create(document.querySelector('#id_text'))
      .catch(error => {
        console.error(error);
      });
  </script>
{% endblock %}

djangock/apps/blog/templates/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col-md">
      <h1>Hello world</h1>
      <small>
        This is a little and dumb project to show integration of
        CKEditor with Django.
      </small>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md">
      <h2>Posts entries</h2>
    </div>
    <div class="col-md">
      <a href="{% url 'blog:create' %}" class="btn btn-info">
        New post
      </a>
    </div>
  </div>
  {% for object in object_list %}
    <div class="row">
      <div class="col-md">
        <a href="{% url 'blog:detail' object.slug %}">
          {{ object.title }}
        </a>
      </div>
    </div>
  {% endfor %}

{% endblock %}

djangock/apps/blog/templates/view_post.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col-md">
      <h2>{{ postentry.title }}</h2>
    </div>
    <div class="col-sm">
      <a href="{% url 'blog:update' postentry.slug %}" class="btn btn-info">
        Edit post
      </a>
      <a href="{% url 'blog:index' %}" class="btn btn-primary">
        Back to list
      </a>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md">
      {{ postentry.text|safe }}
    </div>
  </div>
{% endblock %}